### PR TITLE
Update to v0.10.0

### PR DESCRIPTION
**Pull request by vtermanis**
- Updated lz4 to v1.8.0
- Support for fast acceleration via negative compression levels
- Support for block checksums

### CODE REVIEW

**Comment by jakirkham** [comment]
Would also recommend [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` 2.4.0.

**Comment by vtermanis** [comment]
@jakirkham - Ok, shall do that. Should I make  pull request also or just commit to master for that? (Am waiting for MacOs builds to run first.)

**Comment by jakirkham** [comment]
Would recommend doing a PR. Yeah Travis CI is working through some issues. Might be a bit slow until those are resolved.

**Comment by vtermanis** [comment]
@jakirkham : I updated to conda-smithy 2.4.0. I initially got the same error as https://github.com/conda-forge/conda-smithy/issues/552, but conda-build-all is already 1.1.1. So I downgraded to conda 4.3.22 but now I get:
```
$ conda smithy rerender
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Fetching package metadata ...........
Traceback (most recent call last):
  File "/home/vt/anaconda3/bin/conda-smithy", line 6, in <module>
    exit(main())
  File "/home/vt/anaconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 290, in main
    args.subcommand_func(args)
  File "/home/vt/anaconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 194, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/home/vt/anaconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 723, in main
    render_travis(env, config, forge_dir)
  File "/home/vt/anaconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 243, in render_travis
    if meta.noarch:
AttributeError: 'MetaData' object has no attribute 'noarch'
```

I don't know what else to try at this point.

**Comment by jakirkham** [comment]
What version of `conda-build` are you using? Should be `2.1.x` where `x` is latest.

**Comment by vtermanis** [comment]
```
$ conda list | grep -E "^conda-"
conda-build               2.1.4                    py36_1    conda-forge
conda-build-all           1.1.1                      py_2    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-smithy              2.4.0                      py_1    conda-forge
conda-verify              2.0.0                    py36_0  
```

**Comment by jakirkham** [comment]
Just for verification, what is the result of `conda list -n root conda`?

**Comment by vtermanis** [comment]
```
# packages in environment at /home/vt/anaconda3:
#
anaconda                  4.4.0               np112py36_0  
anaconda-client           1.6.3                    py36_0    conda-forge
anaconda-navigator        1.6.2                    py36_0  
anaconda-project          0.6.0                    py36_0  
conda                     4.3.22                   py36_0    conda-forge
conda-build               2.1.4                    py36_1    conda-forge
conda-build-all           1.1.1                      py_2    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-smithy              2.4.0                      py_1    conda-forge
conda-verify              2.0.0                    py36_0 
```

**Comment by vtermanis** [comment]
@jakirkham: Using a fresh install of miniconda with the following packages and now it works (see #5):
```
# packages in environment at /home/vt/miniconda3:
#
anaconda-client           1.6.5                      py_0    conda-forge
conda                     4.3.23                   py36_0    conda-forge
conda-build               2.1.17                   py36_0    conda-forge
conda-build-all           1.1.1                      py_2    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-smithy              2.4.0                      py_1    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
```

**Pull request merged**
